#!/bin/sh

echo '#ifndef __EDELIB_DBUS_EXPLORER_HELP_H__'
echo '#define __EDELIB_DBUS_EXPLORER_HELP_H__'
echo ''

echo '/* Autogenerated from edelib-dbus-explorer.txt. Edit that file, not this one. */'
echo 'static const char help_content[] ='
sed -e 's/\\/\\\\/g' \
    -e 's/"/\\"/g'   \
	-e 's/\(.*\)/    "\1\\n"/' 
echo ';'
echo '#endif'
