#!/bin/sh
# Convert .scm file to C string. Use as: 'cat file.scm | ./gen-c-string.sh' and revise scm_content variable.
echo '/* Generated with gen-c-string.sh. Do not edit this file, edit .scm file */'
echo 'static const char scm_content[] ='
sed -e '/^\s*$/d' \
	-e '/^\s*;/d' \
	-e 's/"/\\"/g' \
	-e 's/\(.*\)/    " \1 "/' \
	-e 's///g'
echo ';'
